bankuru/urls.py
from django.urls import path

from . import views
from .views import IndexView, ChartData, TermsOfUse

app_name = 'bankuru'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('api/chart/data', ChartData.as_view(), name='chart-data'),
    path('debt_list', views.DebtListView.as_view(), name='debt_list'),
    path('debt_detail/<int:pk>', views.DebtDetailView.as_view(), name='debt_detail'),
    path('debt_form', views.DebtCreateView.as_view(), name='debt_create'),
    path('debt_update/<int:pk>', views.DebtUpdateView.as_view(), name='debt_update'),
    path('debt_delete/<int:pk>', views.DebtDeleteView.as_view(), name='debt_delete'),
    path('charts', views.Charts, name='charts'),
    path('login', views.LoginView.as_view(), name='login'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('terms_of_use', views.TermsOfUse.as_view(), name='terms_of_use'),
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user_update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
]

vanapp2/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('bankuru/', include('bankuru.urls')),
    path('admin/', admin.site.urls),
]

bankuru/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from dateutil.relativedelta import relativedelta
from django.db.models import Count, Sum, Avg, Min, Max


class Debt(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    bank_name = models.CharField("銀行名", max_length=64)
    principal = models.PositiveIntegerField("元本")
    first_payment_date = models.DateField("初回返済日")
    last_payment_date = models.DateField("最終返済日", blank=True)
    first_payment_amount = models.PositiveIntegerField("初回返済額")
    second_payment_amount = models.PositiveIntegerField("二回目返済額")
    payment_terms = models.PositiveIntegerField("返済回数")
    interest = models.FloatField("金利", default=0)
    is_kyokai = models.BooleanField("保証協会あり", default=False)
    is_tanpo = models.BooleanField("担保あり", default=False)
    is_dhosho = models.BooleanField("代表者保証あり", default=False)
    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.bank_name) + '-元本' + str(self.principal) + '-現在残高' + str(self.get_current(0))


    def get_thousand_principal(self):
        thousand_principal = round(self.principal / 1000)
        return thousand_principal

    def get_thousand_monthly1(self):
        thousand_monthly1 = round(self.first_payment_amount / 1000)
        return thousand_monthly1

    def get_thousand_monthly2(self):
        thousand_monthly2 = round(self.second_payment_amount / 1000)
        return thousand_monthly2


    def get_month_value(self):
        y_value = self.first_payment_date.year - 1900 + 1
        m_value = self.first_payment_date.month
        month_value = y_value * 12 + m_value
        return month_value

    
    def get_last_payment_date(self):
        return last_payment_date


    def reverse_month_value(self):
        month = self % 12
        year = self - 1900 - month
        return year, month


    def get_current(self, kagetsu):
        today = timezone.now().date()
        t_year_value = today.year - 1900 +1
        t_month_value = t_year_value * 12 + today.month + kagetsu
        f_month_value = self.get_month_value()       
        X = t_month_value - f_month_value
        if  X < 1:
            current_balance = self.principal
        else:
            current_balance = self.principal - self.first_payment_amount - self.second_payment_amount * X
            if current_balance < 0:
               current_balance = 0
        return current_balance


    def get_current_0(self):
        balance = round(self.get_current(0) / 1000 )
        return balance

    def get_current_1(self):
        balance = round(self.get_current(1) / 1000 )
        return balance

    def get_current_2(self):
        balance = round(self.get_current(2) / 1000 )
        return balance

    def get_current_3(self):
        balance = round(self.get_current(3) / 1000 )
        return balance

    def get_current_4(self):
        balance = round(self.get_current(4) / 1000 )
        return balance

    def get_current_5(self):
        balance = round(self.get_current(5) / 1000 )
        return balance

    def get_current_6(self):
        balance = round(self.get_current(6) / 1000 )
        return balance

    def get_current_7(self):
        balance = round(self.get_current(7) / 1000 )
        return balance

    def get_current_8(self):
        balance = round(self.get_current(8) / 1000 )
        return balance

    def get_current_9(self):
        balance = round(self.get_current(9) / 1000 )
        return balance

    def get_current_10(self):
        balance = round(self.get_current(10) / 1000 )
        return balance

    def get_current_11(self):
        balance = round(self.get_current(11) / 1000 )
        return balance

    def get_current_12(self):
        balance = round(self.get_current(12) / 1000 )
        return balance

    def get_current_24(self):
        balance = round(self.get_current(24) / 1000 )
        return balance

    def get_current_36(self):
        balance = round(self.get_current(36) / 1000 )
        return balance

    def get_current_48(self):
        balance = round(self.get_current(48) / 1000 )
        return balance

    def get_current_60(self):
        balance = round(self.get_current(60) / 1000 )
        return balance


    def get_count(self):
        return self.objects.aggregate(Count('bank_name'))

bankuru/forms.py
from django import forms
from .models import Debt, User
from django.contrib.auth.forms import (
    AuthenticationForm
)
 
 
class LoginForm(AuthenticationForm):
    """ログインフォーム"""
 
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class DebtForm(forms.ModelForm):
    class Meta:
        model = Debt
        fields = ['user', 'bank_name','principal','first_payment_date',
        'last_payment_date','first_payment_amount',
        'second_payment_amount','payment_terms','interest' ]
        
        
class UserUpdateForm(forms.ModelForm): 
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')
 
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class UserCreateForm(forms.ModelForm): 
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')

bankuru/views.py
from django.conf import settings
from django.contrib import messages
from django.shortcuts import render, redirect, resolve_url
from django.views.generic import View, ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from django.utils import timezone
from dateutil.relativedelta import relativedelta
from django.http import JsonResponse
from .models import Debt, User
from .forms import LoginForm, DebtForm, UserUpdateForm
from rest_framework.views import APIView
from rest_framework.response import Response
from django.contrib.auth.views import (
    LoginView, LogoutView
)
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.db.models import Count, Sum, Avg, Min, Max

User = get_user_model()


class OnlyYouMixin(UserPassesTestMixin):
    raise_exception = True
 # 今ログインしてるユーザーのpkと、そのユーザー情報ページのpkが同じなら許可
    def test_func(self):
        user = self.request.user
        return user.pk == self.kwargs['pk']
 
 
class UserDetail(OnlyYouMixin, DetailView):
    model = User
    template_name = 'bankuru/user_detail.html'
 
 
class UserUpdate(OnlyYouMixin, UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'bankuru/user_form.html'
 
    def get_success_url(self):
        return resolve_url('bankuru:user_detail', pk=self.kwargs['pk'])


# @login_required
class IndexView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        data = Debt.objects.filter(active=True).filter(user = self.request.user).order_by('-first_payment_date')[:5]
        kagetsu = 0
        if data:
            current_total_balance = round(get_current_total_balance(data, kagetsu) / 1000)
            current_total_payment = round(get_current_total_payment(data, kagetsu) / 1000)
            current_total_interest = round(get_current_total_interest(data, kagetsu))
            current_weighted_average_interest = round((current_total_interest
             / (current_total_balance * 1000))*100*12,2)
        else:
            current_total_balance = 0
            current_total_payment = 0
            current_total_interest = 0
            current_weighted_average_interest = 0

        params = {
            "title": 'ダッシュボード',
            "data": data,
            "current_total_balance": current_total_balance,
            "current_total_payment": current_total_payment,
            "current_total_interest": current_total_interest,
            "current_weighted_average_interest": current_weighted_average_interest,
            }
        return render(request, 'bankuru/index.html', params)


class ChartData(APIView):

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)  

    authentication_classes = []
    permission_classes = []

    def get(self, request, format=None):
        def get_data(self):
            return Debt.objects.filter(active=True).filter(user=1)
        # data = Debt.objects.filter(active=True).filter(user = 1)
        kagetsu = 0
        labels = get_chart_label(get_data(self))
        default_items = get_chart_data(get_data(self), kagetsu)
        
        data = {
            "labels": labels,
            "default": default_items,
        }
        return Response(data)


class DebtListView(LoginRequiredMixin, ListView):
    model = Debt
    paginate_by = 10

    def get_queryset(self):
        return Debt.objects.filter(user=self.request.user).filter(active=True).order_by('bank_name')


class DebtDetailView(LoginRequiredMixin, DetailView):
    model = Debt


class DebtCreateView(LoginRequiredMixin, CreateView):
    model = Debt
    # fields = ('bank_name', ) 
    form_class = DebtForm
    # form_class.user = get_user_model()
    # initial={'user': get_initial()}
    success_url = reverse_lazy('bankuru:debt_list')
    template_name = 'bankuru/debt_create_form.html'

    # def get_initial(self):
    #     return {'user': get_user_model()}

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(
            self.request, '「{}」を登録しました'.format(form.instance))
        return result
    

class DebtUpdateView(LoginRequiredMixin, UpdateView):
    model = Debt
    form_class = DebtForm
    success_url = reverse_lazy('bankuru:debt_list')
    template_name = 'bankuru/debt_update_form.html'

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(
            self.request, '「{}」を更新しました'.format(form.instance))
        return result


class DebtDeleteView(LoginRequiredMixin, DeleteView):
    model = Debt
    form_class = DebtForm
    success_url = reverse_lazy('bankuru:debt_list')

    def delete(self, request, *args, **kwargs):
        result = super().delete(request, *args, **kwargs)
        messages.success(
            self.request, '「{}」を削除しました'.format(self.object))
        return result


class TermsOfUse(TemplateView):
    template_name = 'terms_of_use.html' 


def get_current_total_balance(data, kagetsu):
    current_total_balance = 0
    for item in data:
        current_total_balance += item.get_current(kagetsu)
    return current_total_balance


def get_current_total_payment(data, kagetsu):
    current_total_payment = 0
    for item in data:
        current_total_payment += item.second_payment_amount
    return current_total_payment


def get_current_total_interest(data, kagetsu):
    current_total_interest = 0
    for item in data:
        current_total_interest += ( item.get_current(kagetsu) * item.interest /100 / 12)
    return current_total_interest


def get_share(data, kagetsu):
    return share

def get_chart_data(data, kagetsu):
    chart_data = []
    for item in data:
        chart_data.append(item.get_current(kagetsu))
    return chart_data


def get_chart_label(data):
    chart_labels = []
    for item in data:
        chart_labels.append(item.bank_name)
    return chart_labels


class LoginView(LoginView):
    form_class = LoginForm
    template_name = 'bankuru/login.html'


class LogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'bankuru/index.html'


def Charts(request):
    return render(request, 'bankuru/charts.html')

    

bankuru/templates/bankuru/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Bankuru</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static 'material_admin/vendor/bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="{% static 'material_admin/vendor/font-awesome/css/font-awesome.min.css' %}">
    <!-- Fontastic Custom icon font-->
    <link rel="stylesheet" href="{% static 'material_admin/css/fontastic.css' %}">
    <!-- Google fonts - Poppins -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,700">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'material_admin/css/style.default.css' %}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'material_admin/css/custom.css' %}">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'material_admin/img/favicon.ico' %}">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
<!-- Chartを使うために追加 -->
    <script src="{% static 'material_admin/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'material_admin/js/charts-custom.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.js"></script>
    <script src="{% static 'material_admin/js/charts-home.js' %}"></script>
   

  </head>
  <body>
    <div class="page">
      <!-- Main Navbar-->
      <header class="header">
        <nav class="navbar">
          <!-- Search Box-->
          <div class="search-box">
            <button class="dismiss"><i class="icon-close"></i></button>
            <form id="searchForm" action="#" role="search">
              <input type="search" placeholder="What are you looking for..." class="form-control">
            </form>
          </div>
          <div class="container-fluid">
            <div class="navbar-holder d-flex align-items-center justify-content-between">
              <!-- Navbar Header-->
              <div class="navbar-header">
                <!-- Navbar Brand --><a href="{% url 'bankuru:index' %}" class="navbar-brand d-none d-sm-inline-block">
                  <div class="brand-text d-none d-lg-inline-block"><strong>Bankuru</strong></div>
                  <div class="brand-text d-none d-sm-inline-block d-lg-none"><strong>Bankuru</strong></div></a>
                <!-- Toggle Button--><a id="toggle-btn" href="#" class="menu-btn active"><span></span><span></span><span></span></a>
              </div>
              <!-- Navbar Menu -->
              <ul class="nav-menu list-unstyled d-flex flex-md-row align-items-md-center">
                <!-- Search
                <li class="nav-item d-flex align-items-center"><a id="search" href="#"><i class="icon-search"></i></a></li> -->
                <!-- Messages                        -->
                <li class="nav-item dropdown"> <a id="messages" rel="nofollow" data-target="#" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link"><i class="fa fa-envelope-o"></i><span class="badge bg-orange badge-corner">3</span></a>
                  <ul aria-labelledby="notifications" class="dropdown-menu">
                    <li><a rel="nofollow" href="#" class="dropdown-item d-flex"> 
                        <div class="msg-body">
                          <h3 class="h5">Jason Doe</h3><span>Sent You Message</span>
                        </div></a></li>
                    <li><a rel="nofollow" href="#" class="dropdown-item d-flex"> 
                        <div class="msg-body">
                          <h3 class="h5">Frank Williams</h3><span>Sent You Message</span>
                        </div></a></li>
                    <li><a rel="nofollow" href="#" class="dropdown-item d-flex"> 
                        <div class="msg-body">
                          <h3 class="h5">Ashley Wood</h3><span>Sent You Message</span>
                        </div></a></li>
                    <li><a rel="nofollow" href="#" class="dropdown-item all-notifications text-center"> <strong>すべてのメッセージを見る</strong></a></li>
                  </ul>
                </li>
                <!-- Logout    -->
                {% if user.is_authenticated %}
                <li class="nav-item dropdown"> <a href="#" data-toggle="dropdown" aria-haspopup="true" class="nav-link">{{ user.get_username }}</a>
                  <ul class="dropdown-menu">
                      <li><a rel="nofollow" href="#" class="dropdown-item d-flex"> 
                          <div class="msg-body">
                            <h3 class="h5"><a class="nav-item nav-link" href="{% url 'bankuru:user_detail' user.pk %}">マイページ</a></h3>
                          </div>
                      </li>
                  </ul>
                </li>
                <li class="nav-item">　　<a href="{% url 'bankuru:logout' %}">Logout</a></li>
                {% else %}
                <li>登録</li>
                <li class="nav-item"><a href="{% url 'bankuru:login' %}"> <span class="d-none d-sm-inline"><button type="button" class="btn btn-primary btn-sm">Login</button></span></a></li>
                {% endif %}

              </ul>
            </div>
          </div>
        </nav>
      </header>

      <div class="page-content d-flex align-items-stretch"> 
        <!-- Side Navbar -->
        <nav class="side-navbar">
          <!-- Sidebar Header-->
          <div class="sidebar-header d-flex align-items-center">
            <div class="avatar"><img src="{% static 'img/logo-transparent.png' %}" alt="..." class="img-fluid rounded-circle"></div>
            <div class="title">
              <h1 class="h4">株式会社サンプル</h1>
              <p>Slogan</p>
            </div>
          </div>
          <!-- Sidebar Navidation Menus--><span class="heading">メインメニュー</span>
          <ul class="list-unstyled">
                    <li class="active"><a href="{% url 'bankuru:index' %}"> <i class="icon-home"></i>ホーム</a></li>
                    <li><a href="{% url 'bankuru:debt_list' %}"> <i class="icon-grid"></i>借入一覧表</a></li>
                    <li><a href="{% url 'bankuru:charts' %}"> <i class="fa fa-bar-chart"></i>借入推移グラフ</a></li>
                    <li><a href="forms.html"> <i class="icon-padnote"></i>詳細分析</a></li>
                    <li><a href="#exampledropdownDropdown" aria-expanded="false" data-toggle="collapse"> <i class="icon-interface-windows"></i>インフォメーション</a>
                      <ul id="exampledropdownDropdown" class="collapse list-unstyled ">
                        <li><a href="#">お知らせ一覧</a></li>
                        <li><a href="#">ニュース</a></li>
                        <li><a href="#">アーカイブ</a></li>
                      </ul>
                    </li>
                    <li><a href="http://127.0.0.1:8000/admin/" target="blank"> <i class="icon-interface-windows"></i>管理者ログイン</a></li>
          </ul>
          <hr>
          <span class="heading">その他</span>
          <ul class="list-unstyled">
            <li> <a href="#"> <i class="icon-flask"></i>機能のご提案</a></li>
            <li> <a href="#"> <i class="icon-screen"></i>会計事務所検索</a></li>
            <li> <a href="#"> <i class="icon-mail"></i>お問い合わせ</a></li>
          </ul>
          <hr>
          <span class="heading"></span>
          <ul class="list-unstyled">
            <li> <a href="#"> <i class="icon-flask"></i>About</a></li>
            <li> <a href="{% url 'bankuru:terms_of_use' %}"> <i class="icon-screen"></i>利用規約</a></li>
            <li> <a href="#"> <i class="icon-mail"></i>プライバシーポリシー</a></li>
          </ul>
        </nav>
        <div class="content-inner">
          <!-- Page Header-->
          <header class="page-header">
            <div class="container-fluid">
              <h2 class="no-margin-bottom">{{ title }}</h2>
            </div>
          </header>

          <!-- Django のメッセージに記録している内容があればここで表示 -->
          {% if messages %}
          <div class="container">
            <div class="row">
              <div class="col-12">
                <div class="messages mt-3">
                  {% for message in messages %}
                    <div class="alert alert-dismissable alert-{{ message.tags }}" data-alert="alert">
                      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                      {{ message }}
                    </div>
                  {% endfor %}
                </div>
              </div>
            </div>
          </div>
          {% endif %}
          <!-- Dashboard Counts Section-->

          {% block content %}
          {% endblock %}

          <!-- Page Footer-->
          <footer class="main-footer">
            <div class="container-fluid">
              <div class="row">
                <div class="col-sm-6">
                  <p>VanCreworth &copy; 2018-</p>
                </div>
                <div class="col-sm-6 text-right">
                  <p>Produced by VanCreworth</p>
                </div>
              </div>
            </div>
          </footer>
        </div>
      </div>
    </div>
    <!-- JavaScript files-->
    <script src="{% static 'material_admin/vendor/popper.js/umd/popper.min.js' %}"> </script>
    <script src="{% static 'material_admin/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'material_admin/vendor/jquery.cookie/jquery.cookie.js' %}"> </script>
    <script src="{% static 'material_admin/vendor/jquery-validation/jquery.validate.min.js' %}"></script>
    <!-- Main File-->
    <script src="{% static 'material_admin/js/front.js' %}"></script>

    {% block script %}
    {% endblock %}

  </body>
</html>

bankuru/templates/bankuru/debt_detail.html
{% extends 'bankuru/base.html' %}
{% load humanize %}
{% block title %}
{{ title }}
{% endblock %}

{% block content %}
<section class="tables">   
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-header d-flex align-items-center">
            <h3 class="h4">借入詳細</h3>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table">
                <thead>
                  <tr>
                    <th>金融機関名</th>
                    <th>返済期間</th>
                    <th>元本</th>
                    <th>金利</th>
                    <th>協会/プロパー</th>
                    <th>現在残高</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>                   
                    <th scope="row">{{ object.bank_name }}</th>
                    <td>{{object.first_payment_date.year }}.{{object.first_payment_date.month }}
                       - {{object.last_payment_date.year }}.{{object.last_payment_date.month }}
                       ({{ object.payment_terms }}回)</td>
                    <td>{{ object.principal|intcomma }}円</td>
                    <td>{{ object.interest }}%</td>
                    <td></td>
                    <td>{{ object.get_current_0|intcomma }}円</td>
                  </tr>
                </tbody>
              </table>
              <hr>
              <a href="{% url 'bankuru:debt_update' object.id %}" class="btn btn-primary">
                編集</a>
                 <a href="{% url 'bankuru:debt_delete' object.id %}" class="btn btn-danger">
                  削除</a> <a href="{% url 'bankuru:debt_list' %} " class="btn btn-outline-secondary">借入一覧表へ戻る</a>
            </div>
          </div>
        </div>

        <div class="card">
          <div class="card-header d-flex align-items-center">
            <h3 class="h4">残高推移（1年） 千円</h3>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table">
                <thead>
                  <tr>
                    <th>1ヶ月後</th>
                    <th>2</th>
                    <th>3</th>
                    <th>4</th>
                    <th>5</th>
                    <th>6</th>
                    <th>7</th>
                    <th>8</th>
                    <th>9</th>
                    <th>10</th>
                    <th>11</th>
                    <th>12</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>                   
                    <td>{{ object.get_current_1|intcomma }}</td>
                    <td>{{ object.get_current_2|intcomma }}</td>
                    <td>{{ object.get_current_3|intcomma }}</td>
                    <td>{{ object.get_current_4|intcomma }}</td>
                    <td>{{ object.get_current_5|intcomma }}</td>
                    <td>{{ object.get_current_6|intcomma }}</td>
                    <td>{{ object.get_current_7|intcomma }}</td>
                    <td>{{ object.get_current_8|intcomma }}</td>
                    <td>{{ object.get_current_9|intcomma }}</td>
                    <td>{{ object.get_current_10|intcomma }}</td>
                    <td>{{ object.get_current_11|intcomma }}</td>
                    <td>{{ object.get_current_12|intcomma }}</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
        
        
        <div class="card">
          <div class="card-header d-flex align-items-center">
            <h3 class="h4">残高推移（隔年・5年） 千円</h3>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table">
                <thead>
                  <tr>
                    <th>1</th>
                    <th>2</th>
                    <th>3</th>
                    <th>4</th>
                    <th>5</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>                   
                    <td>{{ object.get_current_12|intcomma }}</td>
                    <td>{{ object.get_current_24|intcomma }}</td>
                    <td>{{ object.get_current_36|intcomma }}</td>
                    <td>{{ object.get_current_48|intcomma }}</td>
                    <td>{{ object.get_current_60|intcomma }}</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>     




      </div>
    </div>
  </div>

  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-6">
        <div class="card">
          <div class="card-header d-flex align-items-center">
            <h3 class="h4">ノート</h3>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <p>借入時の背景を記載</p>

            </div>
          </div>
        </div>
      </div>

      <div class="col-lg-6">
        <div class="card">
          <div class="card-header d-flex align-items-center">
            <h3 class="h4">データ情報</h3>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table">
                <thead>
                  <tr>
                    <th>登録者</th>
                    <th>登録日時</th>
                    <th>更新日時</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>                   
                    <td>{{ object.user }}</td>
                    <td>{{ object.created_at }}</td>
                    <td>{{ object.updated_at }}</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>



</section>
{% endblock %}

bankuru/templates/bankuru/debt_list_tab3.html
{% load humanize %}
<p>tab3</p>

bankuru/templates/bankuru/terms_of_use.html
{% extends 'bankuru/base.html' %}
{% block title %}
利用規約
{% endblock %}

{% block content %}
あ

{% endblock %}